DROP TABLE IF EXISTS alerts;
CREATE TABLE alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sku INTEGER NOT NULL,
    product TEXT NOT NULL,
    atc_url TEXT NOT NULL,
    product_url TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);